const UIT_2026=5500;
const money=v=>Math.round((Number(v)+Number.EPSILON)*100)/100;
const n=v=>Math.max(0,Number(v)||0);
function balance(tax,credits){const amount=money(tax-n(credits));return{credits:money(n(credits)),balance:Math.abs(amount),balanceType:amount>0?'fisco':amount<0?'contribuyente':'sin_saldo'}}
function first(i){const monthlyRent=n(i.monthlyRent),months=Math.min(12,Math.floor(n(i.monthsReceived))),gross=money(n(i.grossIncome)||(monthlyRent*months)),assessedValue=n(i.assessedValue),presumedGross=money(assessedValue*.06*(months/12)),annualGross=money(Math.max(gross,presumedGross)),deduction=money(annualGross*.2),net=money(annualGross-deduction),tax=money(net*.0625),rentTax=money(gross*.05),minimumTax=money(presumedGross*.05);return{monthlyRent,monthsReceived:months,grossIncome:gross,assessedValue,presumedGrossIncome:presumedGross,annualGrossIncome:annualGross,rentTax,minimumTax,comparisonApplied:presumedGross>gross,deduction20:deduction,taxableIncome:net,calculatedTax:tax,...balance(tax,i.credits)}}
function second(i){const salePrice=n(i.salePrice)||n(i.grossSale),acquisitionCost=n(i.acquisitionCost),correctionIndex=n(i.correctionIndex)||1,updatedCost=money(acquisitionCost?acquisitionCost*correctionIndex:n(i.computableCost)),capitalGain=money(Math.max(0,salePrice-updatedCost)),soleHome=Boolean(Number(i.isSoleHome))&&n(i.ownershipYears)>=2,acquiredBefore2004=Boolean(Number(i.acquiredBefore2004));let exemptionReason='';if(soleHome)exemptionReason='Casa habitación: es tu único inmueble y fuiste propietario por al menos 2 años.';else if(acquiredBefore2004)exemptionReason='El inmueble fue adquirido antes del 1 de enero de 2004.';else if(capitalGain<=0)exemptionReason='No existe ganancia porque el precio de venta no supera el costo actualizado.';const taxableGain=exemptionReason?0:capitalGain,deduction=money(taxableGain*.2),net=money(taxableGain-deduction),tax=money(net*.0625);return{salePrice,acquisitionCost,correctionIndex,updatedCost,capitalGain,exempt:Boolean(exemptionReason),exemptionReason,grossIncome:taxableGain,deduction20:deduction,netIncome:net,taxableIncome:net,effectiveRate:5,calculatedTax:tax,...balance(tax,i.credits)}}
function third(i){const revenue=n(i.revenue),costs=n(i.costs),expenses=n(i.deductibleExpenses),taxable=money(Math.max(0,revenue-costs-expenses+n(i.taxAdditions)-n(i.compensableLoss))),rate=Math.min(1,n(i.rate||29.5)/100),tax=money(taxable*rate);return{revenue,accountingResult:money(revenue-costs-expenses),taxableIncome:taxable,appliedRate:money(rate*100),calculatedTax:tax,advisory:true,...balance(tax,i.credits)}}
function progressiveTax(taxable,uit=UIT_2026){const brackets=[[5*uit,.08],[15*uit,.14],[15*uit,.17],[10*uit,.20],[Infinity,.30]];let remaining=taxable,tax=0;const detail=[];for(const [limit,rate] of brackets){const base=Math.min(remaining,limit);if(base<=0)break;const part=money(base*rate);detail.push({base:money(base),rate:rate*100,tax:part});tax+=part;remaining-=base}return{tax:money(tax),detail}}
function work(i,category){const uit=n(i.uit)||UIT_2026,fourth=category===5?0:n(i.fourthIncome),fifth=category===4?0:n(i.fifthIncome),d20=money(Math.min(fourth*.2,24*uit)),before=money(fourth-d20+fifth),d7=money(Math.min(before,7*uit)),d3=money(Math.min(n(i.additionalExpenses),3*uit,Math.max(0,before-d7))),workNet=money(Math.max(0,before-d7-d3)),foreign=n(i.foreignIncome),maxDonation=money((workNet+foreign)*.1),donation=money(Math.min(n(i.donations),maxDonation)),taxable=money(Math.max(0,workNet-n(i.itf)-donation+foreign)),p=progressiveTax(taxable,uit);return{uit,fourthGross:fourth,fifthGross:fifth,deduction20:d20,deduction7UIT:d7,deduction3UIT:d3,netWorkIncome:workNet,maxDonation,acceptedDonation:donation,taxableIncome:taxable,brackets:p.detail,calculatedTax:p.tax,...balance(p.tax,i.credits)}}
function calculate(category,input={}){const c=Number(category);if(c===1)return first(input);if(c===2)return second(input);if(c===3)return third(input);if(c===4||c===5)return work(input,c);throw new Error('Categoría no válida')}
module.exports={calculate,progressiveTax,UIT_2026};
